name: Setup Environment
description: Setup the environment (Java and Gradle)

runs:
  using: 'composite'
  steps:
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
        cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

    - name: Setup Gradle Properties
      shell: bash
      run: |
        echo "org.gradle.jvmargs=-Xms10g -Xmx10g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC" >> ~/.gradle/gradle.properties
        echo "kotlin.daemon.jvmargs=-Xms4g -Xmx4g -XX:+UseParallelGC" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
        echo "org.gradle.workers.max=2" >> ~/.gradle/gradle.properties
        echo "org.gradle.vfs.watch=false" >> ~/.gradle/gradle.properties                   

    - name: Cache KMP tooling
      uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-v1-${{ hashFiles('*.gradle.kts') }}


