package com.prof18.feedflow.core.utils

object TestingTag {
    const val BACK_BUTTON = "back_button"
    const val BACK_BUTTON_FEED_SOURCES = "back_button_feed_sources"
    const val BACK_BUTTON_FEED_SETTINGS = "back_button_feed_settings"
    const val HOME_SCREEN_ADD_FEED_BUTTON = "home_screen_add_feed_button"
    const val NO_FEED_BOTTOM_SHEET_MESSAGE = "no_feed_bottom_sheet_message"
    const val NO_FEED_BOTTOM_SHEET_ADD_BUTTON = "no_feed_bottom_sheet_add_button"
    const val NO_FEED_BOTTOM_SHEET_IMPORT_BUTTON = "no_feed_bottom_sheet_import_button"
    const val FEED_URL_INPUT = "feed_url_input"
    const val ADD_FEED_BUTTON = "add_feed_button"
    const val INVALID_URL_ERROR_MESSAGE = "invalid_url_error_message"
    const val CATEGORY_SELECTOR = "category_selector"
    const val CATEGORY_TEXT_INPUT = "category_text_input"
    const val ADD_CATEGORY_BUTTON = "add_category_button"
    const val DELETE_CATEGORY_BUTTON = "delete_category_button"
    const val CATEGORY_RADIO_BUTTON = "category_radio_button"
    const val SETTING_BUTTON = "setting_button"
    const val SETTINGS_MENU = "settings_menu"
    const val SETTINGS_FEED_ITEM = "settings_feed_item"
    const val FEED_SOURCE_SELECTOR = "feed_source_selector"
    const val FEED_SOURCE_DELETE_BUTTON = "feed_source_delete_button"
    const val NO_FEED_SOURCE_MESSAGE = "no_feed_source_message"
    const val IMPORT_FEED_OPML_BUTTON = "import_feed_opml_button"
    const val IMPORT_DONE_BUTTON = "import_done_button"
    const val IMPORT_DONE_MESSAGE = "import_done_message"
    const val REFRESH_FEEDS_BUTTON = "refresh_feeds_button"
    const val NO_ITEMS_MESSAGE = "no_items_message"
    const val FEED_ITEM = "feed_item"
    const val LOADING_BAR = "loading_bar"
    const val UNREAD_DOT = "unread_dot"
    const val HOME_TOOLBAR = "home_toolbar"
    const val MARK_AS_READ_SCROLLING_SWITCH = "mark_as_read_scrolling_switch"
    const val BROWSER_SELECTOR = "browser_selector"
    const val ABOUT_SETTINGS_ITEM = "about_settings_item"
    const val ABOUT_TOOLBAR = "about_toolbar"
    const val DRAWER_MENU_BUTTON = "drawer_menu_button"
}
