name: Manual Linux Build
on:
  workflow_dispatch:
    { }

jobs:
  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-gradle
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Update Licenses file
        run: ./gradlew desktopApp:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/

      - name: Create path variables
        id: path_variables
        run: |
          tag=$(git describe --tags --abbrev=0 --match "*-desktop")
          version=$(echo "$tag" | sed 's/-desktop$//')
          name_deb="FeedFlow-${version}.deb"
          path_deb="desktopApp/build/release/main-release/deb/${name}"
          name_rpm="FeedFlow-${version}.rpm"
          path_rpm="desktopApp/build/release/main-release/rpm/${name}"
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "RELEASE_PATH_DEB=$path_deb" >> $GITHUB_ENV
          echo "RELEASE_PATH_RPM=$path_rpm" >> $GITHUB_ENV
          echo "NAME_DEB=$name_deb" >> $GITHUB_ENV
          echo "NAME_RPM=$name_rpm" >> $GITHUB_ENV

      - name: Create Properties file
        run: |
          echo "is_release=true" >> desktopApp/src/jvmMain/resources/props.properties
          echo "sentry_dns=$SENTRY_DNS" >> desktopApp/src/jvmMain/resources/props.properties
          echo "version=$VERSION" >> desktopApp/src/jvmMain/resources/props.properties
          echo "dropbox_key=$DROPBOX_API_KEY" >> desktopApp/src/jvmMain/resources/props.properties
        env:
          SENTRY_DNS: ${{ secrets.SENTRY_DNS }}
          VERSION: ${{ env.VERSION }}
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}

      - name: Create RPM & DEB
        run: ./gradlew packageReleaseDeb packageReleaseRpm

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.RELEASE_PATH_RPM }}
          name: ${{ env.NAME_RPM }}

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.RELEASE_PATH_DEB }}
          name: ${{ env.NAME_DEB }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/compose/logs/*  
