name: Update Website after Desktop Release

on:
  workflow_dispatch: {}
  # release:
  #   types: [released]

jobs:
  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create path variables
        id: path_variables
        run: |
          MAJOR=$(grep "MAJOR=" version.properties | cut -d'=' -f2)
          MINOR=$(grep "MINOR=" version.properties | cut -d'=' -f2)
          PATCH=$(grep "PATCH=" version.properties | cut -d'=' -f2)
          echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Update website
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          # Construct URLs
          DMG_URL="https://github.com/prof18/feed-flow/releases/download/${VERSION}-all/FeedFlow-${VERSION}.dmg"
          MSI_URL="https://github.com/prof18/feed-flow/releases/download/${VERSION}-all/FeedFlow-${VERSION}.msi"
          RPM_URL="https://github.com/prof18/feed-flow/releases/download/${VERSION}-all/feedflow-${VERSION}-1.x86_64.rpm"
          DEB_URL="https://github.com/prof18/feed-flow/releases/download/${VERSION}-all/feedflow_${VERSION}_amd64.deb"
          
          # Update hero.yml
          sed -i "s|button3Link:.*|button3Link: ${DMG_URL}|" website/data/hero.yml
          sed -i "s|button5Link:.*|button5Link: ${RPM_URL}|" website/data/hero.yml
          sed -i "s|button6Link:.*|button6Link: ${DEB_URL}|" website/data/hero.yml
          
          # Update downloads.yml
          sed -i "s|url: \".*\.dmg\"|url: \"${DMG_URL}\"|" website/data/downloads.yml
          sed -i "s|url: \".*\.msi\"|url: \"${MSI_URL}\"|" website/data/downloads.yml
          sed -i "s|url: \".*\.rpm\"|url: \"${RPM_URL}\"|" website/data/downloads.yml
          sed -i "s|url: \".*\.deb\"|url: \"${DEB_URL}\"|" website/data/downloads.yml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: |
          cd website
          HUGO_ENV=production hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/public
